### ISSUE TITLE
Linking to BLT

### ISSUE THREAD

**Issue by DanielO** [apnadkarni/blt#1]
Hi,
We have a shared library which is used to read some data files and set BLT vectors.

Previously we used Tcl/Tk 8.4 and BLT 2.4z but would like to move on so I am trying our code with this BLT.

I am having an issue where I end up with multiple instances of BLT loaded and the BltMallocPtr ends up being NULL in one instance but not another and so I get a segfault.

What is the "right way" for my library to link to BLT? :)

Thanks.

**Comment by apnadkarni** [comment]
I'm afraid I can't immediately be of help because I'm more or less in the same boat as you! I was also looking for a version of BLT that worked well with Tcl 8.6 and forked this repository based on George Howlett's latest work in his SourceForge repository. However, this is still very much work-in-progress, I'm just tracking George's repository as he works on it. My changes are to simply get it to build on Windows platforms. I suspect it will be a little while before he completes this version for production use.

In the meanwhile, I can suggest some alternative forks if you have not tried them as yet - https://github.com/wjoye/tkblt is something being used in production afaik. There is also the RBC toolkit which is also a fork of blt (Refactored BLT Components). Neither of these contain the full original BLT functionality but do have the graphing and vector capabilities which are of interest to me. I don't have any experience with the former but I have my own RBC fork that I have stubs-enabled and am linking with my own application (including vector support). It is at https://github.com/apnadkarni/rbctoolkit if you are interested. If you use it, I am more likely to be able to help than with this BLT fork. I have only tried it on Windows though.

Sorry could not help more

/Ashok

**Comment by DanielO** [comment]
OK fair enough.
I actually did a bit more digging and found I had run the configure script incorrectly earlier and so had an extra library that was getting loaded.

After I cleaned it out and rebuilt it seems to work!
